package hfprop

import (
	"net/http"
	"net/http/httptest"
	"testing"
	"time"
)

var (
	mockFoF2response string = `# Global Ionospheric Radio Observatory
# GIRO Tabulated Ionospheric Characteristics, Version 1.0 Revision B
# Generated by DIDBGetValues on 2023-01-23T21:39:11.337Z
#
# Location: GEO 54.6N 13.4E, URSI-Code JR055 JULIUSRUH
# Instrument: Ionosonde, Model: DPS-4D
#
# Query for measurement intervals of time:
# 2023-01-23T21:00:00.000Z - 2023-01-23T22:00:00.000Z
#
# Data Selection:
# CS is Autoscaling Confidence Score (from 0 to 100, 999 if manual scaling, -1 if unknown)
# foF2 [MHz] - F2 layer critical frequency
#
# All GIRO measurements are released under CC-BY-NC-SA 4.0 license
# Please follow the Lowell GIRO Data Center RULES OF THE ROAD
# https://ulcar.uml.edu/DIDBase/RulesOfTheRoadForDIDBase.htm
# Requires acknowledgement of JR055 data provider
#
#Time                     CS   foF2 QD
2023-01-23T21:03:16.000Z  90  3.075 //
2023-01-23T21:08:16.000Z  70  3.100 //
2023-01-23T21:13:16.000Z  50  3.075 //
2023-01-23T21:18:16.000Z  90  3.125 //
2023-01-23T21:23:16.000Z  90  3.125 //
2023-01-23T21:28:16.000Z  70  3.100 //
2023-01-23T21:33:16.000Z  65  2.975 //
`

	mockHmF2response string = `# Global Ionospheric Radio Observatory
# GIRO Tabulated Ionospheric Characteristics, Version 1.0 Revision B
# Generated by DIDBGetValues on 2023-01-23T21:40:34.838Z
#
# Location: GEO 54.6N 13.4E, URSI-Code JR055 JULIUSRUH
# Instrument: Ionosonde, Model: DPS-4D
#
# Query for measurement intervals of time:
# 2023-01-23T21:00:00.000Z - 2023-01-23T22:00:00.000Z
#
# Data Selection:
# CS is Autoscaling Confidence Score (from 0 to 100, 999 if manual scaling, -1 if unknown)
# hmF2 [km] - Peak height F2-layer
#
# All GIRO measurements are released under CC-BY-NC-SA 4.0 license
# Please follow the Lowell GIRO Data Center RULES OF THE ROAD
# https://ulcar.uml.edu/DIDBase/RulesOfTheRoadForDIDBase.htm
# Requires acknowledgement of JR055 data provider
#
#Time                     CS   hmF2 QD
2023-01-23T21:03:16.000Z  90  356.6 //
2023-01-23T21:08:16.000Z  70  354.5 //
2023-01-23T21:13:16.000Z  50  356.0 //
2023-01-23T21:18:16.000Z  90  374.5 //
2023-01-23T21:23:16.000Z  90  375.8 //
2023-01-23T21:28:16.000Z  70  360.8 //
2023-01-23T21:33:16.000Z  65  635.2 //
2023-01-23T21:38:16.000Z  70  359.1 //
`
)

func TestSetDistanceForMUF(t *testing.T) {
	SetDistanceForMUF(100)
	if DMUF != "100" {
		t.Errorf("Expected 100, got %s", DMUF)
	}
	SetDistanceForMUF(3000.0)
}

func TestGetGiroData(t *testing.T) {
	server := httptest.NewTLSServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.WriteHeader(http.StatusOK)
	}))
	defer server.Close()

	// override base URL with our mock HTTPS server.
	LgdcBaseUrl = server.URL

	gd, err := GetGiroData("hmF2", DefaultUrsiCode, time.Now().Add(-1*time.Hour), time.Now())
	if err != nil {
		t.Fatal(err)
	}
	if len(gd) < 1 {
		t.Fatal("Expected at least one GiroData object, got none")
	}
}
